spring.application.name=schoolmap

server.port=8094
server.servlet.context-path=/api
server.error.include-message=always

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5434/schoolmap_data
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQL95Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect
spring.jpa.show-sql=true

jwt.secret=/sZVRCAD5lbmzilL06enDvknwYz8DVLtp7l7bpn575I=

jwt.expiration=36000000